name: Generate Neon Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: lien0219
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=00F5FF&color_dots=#0d1117,#0d1117,#0d1117,#0d1117,#00F5FF
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=00F5FF

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
